# Generated by Django 4.2 on 2023-04-23 14:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("translator", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Document",
        ),
    ]
